#!/usr/bin/perl
##
##  printenv -- demo CGI program which just prints its environment
##

print "Content-type: text/html\n\n";
print "<html><head><title>grouper</title></head><body>\n";
print "<table border=1>\n";
print "<tr><th>Variable Name</th><th>Variable Value</th></tr>\n";
foreach $var (sort(keys(%ENV))) {
    $val = $ENV{$var};
    $val =~ s|\n|\\n|g;
    $val =~ s|"|\\"|g;
    print "<tr><td>${var}</td><td>\"${val}\"</td></tr>\n";
}
print "</table>\n";
print "<hr><pre>\n";
while (<STDIN>) { print; }
print "</pre></body></html>\n";
exit 0;
