FROM centos:centos7
MAINTAINER TIER

EXPOSE 80
EXPOSE 443

RUN yum -y update

RUN yum install -y httpd mod_ssl python epel-release

RUN mkdir /opt/tier
COPY files/run_httpd.sh /opt/tier
COPY files/printenv files/configGrouper.py /var/www/cgi-bin/
COPY files/configGrouper.html files/configGrouper.css files/favicon.ico files/school_logo.png /var/www/html/
RUN ln -s /var/www/html/configGrouper.html /var/www/html/index.html

RUN chmod 755 /opt/tier/run_httpd.sh

CMD /opt/tier/run_httpd.sh

